---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: microservices-demo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/sympatheticmoose/microservices-demo.git

